/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import NEFHAM.Game;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author ssasa
 */
public class ChooseCategoryAndGame extends javax.swing.JFrame {

    public static String Category="";
    public static String selectedItemStr;
    public static ChooseCategoryAndGame form = new ChooseCategoryAndGame();
    public static String[] arr ;

    public ChooseCategoryAndGame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jButton4 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Categories");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Science");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Math");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("Technology");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Play Game");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButton1.setText("Create Game");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRadioButton1)
                        .addGap(38, 38, 38)
                        .addComponent(jRadioButton2)
                        .addGap(46, 46, 46)
                        .addComponent(jRadioButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1))
                    .addComponent(jButton4)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton3)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97)
                .addComponent(jButton4)
                .addContainerGap(108, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
           
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        Category = "Science";
        try {
            boolean check;
            ArrayList<String> games = Game.chooseCategory(Category);
            jComboBox1.removeAllItems();
            for (int i = 0; i < games.size(); i++) {
                if (jComboBox1.getItemCount() == 0) {
                    jComboBox1.addItem(games.get(i));
                } else {
                    for (int j = 0; j < jComboBox1.getItemCount(); j++) {
                        check = jComboBox1.getItemAt(j).equalsIgnoreCase(games.get(i));
                        if (!check) {
                            jComboBox1.addItem(games.get(i));
                        }
                    }
                }
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(ChooseCategoryAndGame.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        Category = "Math";
        try {
            boolean check;
            ArrayList<String> games = Game.chooseCategory(Category);
            jComboBox1.removeAllItems();
            for (int i = 0; i < games.size(); i++) {
                if (jComboBox1.getItemCount() == 0) {
                    jComboBox1.addItem(games.get(i));
                } else {
                    for (int j = 0; j < jComboBox1.getItemCount(); j++) {
                        check = jComboBox1.getItemAt(j).equalsIgnoreCase(games.get(i));
                        if (!check) {
                            jComboBox1.addItem(games.get(i));
                        }
                    }
                }
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(ChooseCategoryAndGame.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        Category = "Technology";
        try {
            boolean check;
            ArrayList<String> games = Game.chooseCategory(Category);
            jComboBox1.removeAllItems();
            for (int i = 0; i < games.size(); i++) {
                if (jComboBox1.getItemCount() == 0) {
                    jComboBox1.addItem(games.get(i));
                } else {
                    for (int j = 0; j < jComboBox1.getItemCount(); j++) {
                        check = jComboBox1.getItemAt(j).equalsIgnoreCase(games.get(i));
                        if (!check) {
                            jComboBox1.addItem(games.get(i));
                        }
                    }
                }
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(ChooseCategoryAndGame.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            Object selectedItem = jComboBox1.getSelectedItem();
            selectedItemStr = selectedItem.toString();
            ChooseCategoryAndGame.form.setVisible(false);
            PlayGame.form.setVisible(true);
            String s = Game.playGame(selectedItemStr);
            try {
                
                arr = s.split(";");
                PlayGame.jLabel11.setText(arr[0]);
                PlayGame.jLabel13.setText(arr[1]);
                PlayGame.jLabel8.setText(arr[2]);
                PlayGame.jLabel9.setText(arr[3]);
                PlayGame.jLabel5.setText(arr[4]);
                PlayGame.jLabel2.setText(arr[6]);
                String[] answers = new String[4];
                answers = arr[7].split("/");
              

                PlayGame.jComboBox1.removeAllItems();
               /* if (PlayGame.jComboBox1.getItemCount() == 0) {
                        PlayGame.jComboBox1.addItem(answers[0]);*/
                for (int i = 0; (i < answers.length && i < 4); i++) {
                    PlayGame.jComboBox1.addItem(answers[i]);
                        /*for (int j = 0;( j < PlayGame.jComboBox1.getItemCount() && j < 4 ); j++) {
                            
                            check = PlayGame.jComboBox1.getItemAt(j).equalsIgnoreCase(answers[i]);
                            if (!check) {
                                PlayGame.jComboBox1.addItem(answers[i]);
                            }
                        }*/
                    }
                
            } catch (ArrayIndexOutOfBoundsException e) {

            }

        }catch (FileNotFoundException ex) {
            Logger.getLogger(ChooseCategoryAndGame.class.getName()).log(Level.SEVERE, null, ex);

        }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
if (Category.length() ==0)
{
    JOptionPane.showMessageDialog(null,
                            "Please Choose Category.", "Error", JOptionPane.ERROR_MESSAGE);}

else
{
        ChooseCategoryAndGame.form.setVisible(false);
           CreateGame.form.setVisible(true); }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChooseCategoryAndGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChooseCategoryAndGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChooseCategoryAndGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChooseCategoryAndGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChooseCategoryAndGame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    public static javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    public static javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    // End of variables declaration//GEN-END:variables
}
